### ISSUE TITLE
V3 checklist

### ISSUE THREAD

**Issue by bartelink** [jet/propulsion#116]
- [ ] Kafka: target FsKafka/CK `~1.7` https://github.com/jet/FsKafka/issues/48
- [ ] Kafka0: remove see https://github.com/jet/FsKafka/issues/48
- [ ] EventStore, SqlStreamStore: update to target Equinox.* 3.0.0
- [ ] Cosmos: continues to target Equinox.Cosmos >= 2.6.0, so can not be used side by side with Propulsion.* >=3.0.0
- [ ] CosmosStore: target non-preview CFP logic (I believe that will be in Microsofft.Azure.Cosmos 3.21.0)
